### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by laisee** [xemex-io/xemex.web#1]
enable user accounts for site
 - email when signing up
 - email when password lost
 - login via Google, F/B

**Comment by ppantilla** [comment]
setup using google as smtp server, as heroku doesnt allow PHPmail.,

**Comment by ppantilla** [comment]
changing social login plugin and testing.

**Comment by ppantilla** [comment]
clearing browser cache should show the options.  although icons arent displaying.  need to verify if the css needs to be included.  this used to work last year with no problems.

**Comment by ppantilla** [comment]
logging in using incognito browser shows you can login using fb (i.e. no cache)

**Comment by laisee** [comment]
Signing up, resetting password OK. 

Final piece on logging in via google & facebook?

**Comment by ppantilla** [comment]
Setting up google apis for oauth.  Google wont let me use a numeric url though:
![googlapiscreenshot.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/597ad6fe9394f7001a8e429d/125516c66e82c728ace21e0d46ef9b95248e82b986fabc51a158fe87214933316546b3397f8fe62bab0021435a5649ae120e584cf4f98e7df7b33c70895558bfd7385976d42103eee9dc4be05ce36ade0d97bcae884acae93825e58b864c371c0c1e89f64f78.jpg)

**Comment by ppantilla** [comment]
dunno if theres any other way to get this enabled other than actually setting up the TLD

**Comment by laisee** [comment]
can you use e-sports.cool  that is forwarding in to the IP address now

**Comment by ppantilla** [comment]
this is for xemex.  e-sports.cool forwards to bbninja.herokuapp.com.  the error message above gives me the impression that they need a public tld within the url

**Comment by laisee** [comment]
will forward the xemex.co to http://45.58.45.127. then you can try again on Google login

**Comment by ppantilla** [comment]
![duterte_2_1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/597ad6fe9394f7001a8e429d/125516c66e82c728ace21e0d46ec818e269097acb0bb8012e611b2843b492d762a10e17132d0ba7fed417d5657574eab17095a44fcfa8078f4b06976884e17ff933c0120996048e6edc00db513bb228e4c8dbcbd8f4cc2ec3b21e08d8f47381c1755.jpg)

**Comment by laisee** [comment]
xemex.co now forwarding to http://45.58.40.76. See if that enables Google login.

**Comment by laisee** [comment]
Signed up for Steam API Key:
Key: 7C7DC134CFADC4260A57CFCBAF1FFF32
Domain Name: e-sports.cool

**Comment by ppantilla** [comment]
Afraid google API didn't take it, really needs a TLD in the URL methinks.  

400. That’s an error.

Error: invalid_request

Invalid parameter value for redirect_uri: Raw IP addresses not allowed: http://45.58.40.76/flynsarmy/sociallogin/Google/callback

**Comment by ppantilla** [comment]
Configured site with this key.  Having trouble with my steam account but this should be good for testing On Aug 11, 2017 11:55 PM, Wintermute <notifications@github.com> wrote:Signed up for Steam API Key:
Key: 7C7DC134CFADC4260A57CFCBAF1FFF32
Domain Name: e-sports.cool

**Comment by laisee** [comment]
closing except for Google setup, adding hosting for xemex.co URL

**Comment by laisee** [comment]
Works
