### ISSUE TITLE
Ajax handler not found @ xemex(45.58.40.76)

### ISSUE THREAD

**Issue by laisee** [xemex-io/xemex.web#16]
Clicking on "logout" button generates error message - whether user logged in or not.

**Comment by ppantilla** [comment]
Um let me fix up all these then tell you when its ready to review.  Still havent put in the proper hooks was getting the session to work first.On Aug 2, 2017 1:24 PM, Wintermute <notifications@github.com> wrote:Clicking on "logout" button generates error message - whether user logged in or not.

**Comment by ppantilla** [comment]
this is done.  closing, subject of course for review
