### ISSUE TITLE
Create atlantic instance for bbninja

### ISSUE THREAD

**Issue by ppantilla** [xemex-io/xemex.web#21]

**Comment by ppantilla** [comment]
didnt see a ticket for this, thought it might be good to have

**Comment by laisee** [comment]
It's done I sent you the details

**Comment by laisee** [comment]
Your server has been created. Please use the following information listed below to access your new server.
Server Details:
To setup OctoberCMS, please follow this link: http://45.58.45.127/verify.php?=38e1dcfad8dd442b8ee553099f3fcfa4
Server ID: 711306
Server Login:
 IP: 45.58.45.127
 Username: root
 Password: 4dtWqdYJAHGOTXkA
