### ISSUE TITLE
Create Xemex logo

### ISSUE THREAD

**Issue by laisee** [xemex-io/xemex.web#3]
create logo for 
 - Xemex(brand)
 - Xemex:sport (site or sub-site)
 - Xemex:trading (site or sub-site)

**Comment by ppantilla** [comment]
uploading latest version ....
![logostudy3](https://user-images.githubusercontent.com/7598392/28705037-8629f85a-73a0-11e7-9406-ee02fbd00ce8.jpg)

**Comment by ppantilla** [comment]
All work files to date ....



[xemexlogo.zip](https://github.com/xemex-io/xemex.web/files/1182181/xemexlogo.zip)

**Comment by laisee** [comment]
Done done

**Comment by laisee** [comment]
I like option three with skuinny font for the ".CO" extension.
