### ISSUE TITLE
Add "Sport" text in red text next to Icon

### ISSUE THREAD

**Issue by laisee** [xemex-io/xemex.web#31]
same font, same size but in red to make it stand out.

**Comment by ppantilla** [comment]
![logostudyxemexsport.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/597ad6fe9394f7001a8e429d/125516c66e82c728ace21e0d46e49b9d2c9197bc8bf0a746a958e887394935676b48e13b628ae92dbc56395b4d5a47ab430b0943f4f1892cf0e739708a5f02be836b0a72c42f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e7898c473c19051e8cfc5b27ed.jpg)

**Comment by laisee** [comment]
Perfect

Logged in as admin and created/removed an article on home page. It's gone
but I see "Contact" link on right top of home page. Leave you to correct
this as I may have messed up somehow

Gavin

On 11 Aug 2017 12:31 a.m., "Peter Pantilla" <notifications@github.com>
wrote:

[image: logostudyxemexsport.jpg]
<https://camo.githubusercontent.com/02964266cba7b565cd65c7b5ae7d1abc50bed51e/68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3539376164366665393339346637303031613865343239642f31323535313663363665383263373238616365323165306434366534396239643263393139376263386266306137343661393538653838373339343933353637366234386531336236323861653932646263353633393562346435613437616234333062303934336634663138393263663065373339373038613566303262653833366230613732633432663064626566616433343165623565653737396331316163376134623639383465633665323363323065373839386334373363313930353165386366633562323765642e6a7067>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xemex-io/xemex.web/issues/31#issuecomment-321604490>,
or mute the thread

**Comment by ppantilla** [comment]
done

**Comment by laisee** [comment]
Add to the home page also.

**Comment by ppantilla** [comment]
its there.    maybe ou just need to clear your site cache?
