### ISSUE TITLE
Create/Select Font for xemex.io

### ISSUE THREAD

**Issue by laisee** [xemex-io/xemex.web#4]
select or create font for xemex.io web site, which cover xemex:sport and xemex:trading

**Comment by ppantilla** [comment]
same as the one we used ? Have the ttfs for this already + a whole bunch of variants

**Comment by ppantilla** [comment]
[proxima.zip](https://github.com/xemex-io/xemex.web/files/1182169/proxima.zip)

**Comment by ppantilla** [comment]
attached to ticket and uploaded proxima.zip on githuib

**Comment by laisee** [comment]
Done done

**Comment by laisee** [comment]
proxima is fine, same one used in logo I assume - not being a font expert.
