### ISSUE TITLE
Feedback on new Xemex pages

### ISSUE THREAD

**Issue by laisee** [xemex-io/xemex.web#6]
provide feedback on new xemex pages

**Comment by laisee** [comment]
Change "Token Prices" to "Token Markets"

**Comment by laisee** [comment]
move the "Add Token" fields into a popup.

**Comment by laisee** [comment]
Add an About page on Xemex with link to download or request white paper.

**Comment by laisee** [comment]
add standard icons to page footer plus right side of home page
![Screenshot 2017-08-02 12.51.24.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c364167f3e7956e37a22cbb679f1102f43434d0eee1e020a17b8eb8339a3bf3b72d90a0ce5d96d5822973811acbb8b4ced07ef26895d99a4fedb1294b7607caddecd5d340c061983fe5835a19f4fc15df24ee7495db65e.png)

**Comment by laisee** [comment]
Also, refer to other task on standard links for site

**Comment by laisee** [comment]
The choice of yellow/orange background color for buttons makes it hard to read the text on each button. Can you take a look at https://www.usertesting.com/blog/2014/12/02/color-ux-conversion-rates (sure you know this stuff, but good to have common starting point) then we can review the color scheme for Xemex against the questions on that web page

**Comment by laisee** [comment]
tidy up the white paper signup process i.e. remove references to any non-Xemex entites, fix the error when user clicks to "continue to web site" within the confirmation email --> https://laratify.com. Better option would be to simply collect the emails, discarding any duplicates.

**Comment by ppantilla** [comment]
login/logout/registration/members area permissions done
