### ISSUE TITLE
Collect examples of wallet UIs

### ISSUE THREAD

**Issue by laisee** [xemex-io/xemex.web#7]

**Comment by laisee** [comment]
example 1: look at the wallet provided by NEM (code at https://github.com/NemProject/NanoWallet)
![Screenshot 2017-08-01 15.23.34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c364167f3e7955e37a25cbb17bf1112f43434d0eee1e020a17b8eb8339a3bf3b72d90a0ce5d96d5822973811acbb8b4ced07ef26895d99a4fedb1294b7607caddecd5d340c071e83fe5835a19c4cca5af349e34b56b65e.png)

**Comment by laisee** [comment]
www.bitfinex.com
![Screenshot 2017-08-01 15.48.53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c364167f3e7955e37a25cbb770f1172843434d0eee1e020a17b8eb8339a3bf3b72d90a0ce5d96d5822973811acbb8b4ced07ef26895d99a4fedb1294b7607caddecd5d340c061983fe5835a19c4ccb5ff148e44554b65e.png)

**Comment by laisee** [comment]
www.coinhako.com
![Screenshot 2017-08-01 15.51.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c364167f3e7955e37a25cbb679f1122f43434d0eee1e020a17b8eb8339a3bf3b72d90a0ce5d96d5822973811acbb8b4ced07ef26895d99a4fedb1294b7607caddecd5d340c071e83fe5835a19c4ccb50ff4ae34452b65e.png)

**Comment by laisee** [comment]
www.coinbase.com
![Screenshot 2017-08-01 15.54.09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c364167f3e7955e37a25cbb67cf1122243434d0eee1e020a17b8eb8339a3bf3b72d90a0ce5d96d5822973811acbb8b4ced07ef26895d99a4fedb1294b7607caddecd5d340c071e83fe5835a19c4ccc59f34de2495db65e.png)

**Comment by ppantilla** [comment]
![bitconnect.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/597ad6fe9394f7001a8e429d/125516c66e82c728ace21e0d46ea9d8e208d8da78aeaab01e81fe086264c22703d46f96925dcb47abc442c59575f49fa105d5f44fff0da79a0e33a72984019af80330b2b9b645bf9fa9015ad03bc2a8a4a85b7bb8f4dc8eb3426e7839d02.jpg)

**Comment by ppantilla** [comment]
perhaps https://www.coinbase.com/dashboard makes the most sense for us?

**Comment by laisee** [comment]
Makes sense as Accounts page. Might want to have smaller charts . Let's
chat about next step as the NEM wallet available to drop (or force) into
the web site html

**Comment by laisee** [comment]
adding task to backlog for inserting NEM wallet html. styling can be adapated to mirror Coinbase
