### ISSUE TITLE
Collect examples of ticker UIs

### ISSUE THREAD

**Issue by laisee** [xemex-io/xemex.web#8]

**Comment by laisee** [comment]
[Uploading Screenshot 2017-08-01 15.38.38.png...]

**Comment by laisee** [comment]
![Screenshot 2017-08-01 15.40.07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c364167f3e7955e37a25cbb778f1122c43434d0eee1e020a17b8eb8339a3bf3b72d90a0ce5d96d5822973811acbb8b4ced07ef26895d99a4fedb1294b7607caddecd5d340c071e83fe5835a19c4ccb5af44be94456b65e.png)

www.bitfinex.com

**Comment by laisee** [comment]
www.coinhako.com
[Uploading Screenshot 2017-08-01 15.41.25.png...]

**Comment by laisee** [comment]
www.gdax.com
![Screenshot 2017-08-01 15.45.43.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c364167f3e7955e37a25cbb77df1162843434d0eee1e020a17b8eb8339a3bf3b72d90a0ce5d96d5822973811acbb8b4ced07ef26895d99a4fedb1294b7607caddecd5d340c071e83fe5835a19c4ccb5df142e64c5db65e.png)

**Comment by ppantilla** [comment]
checking out widgets available from https://bitcoinaverage.com.

**Comment by laisee** [comment]
adding task to backlog for inserting widget to page(s)
